/*******************************************************************************
* Copyright (C) 2013-2015, Cypress Semiconductor Corporation. All rights reserved.
*
* This software, including source code, documentation and related
* materials "Software", is owned by Cypress Semiconductor
* Corporation "Cypress" and is protected by and subject to worldwide
* patent protection (United States and foreign), United States copyright
* laws and international treaty provisions. Therefore, you may use this
* Software only as provided in the license agreement accompanying the
* software package from which you obtained this Software "EULA".
* If no EULA applies, Cypress hereby grants you a personal, nonexclusive,
* non-transferable license to copy, modify, and compile the
* Software source code solely for use in connection with Cypress's
* integrated circuit products. Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO
* WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
* BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
* PARTICULAR PURPOSE. Cypress reserves the right to make
* changes to the Software without notice. Cypress does not assume any
* liability arising out of the application or use of the Software or any
* product or circuit described in the Software. Cypress does not
* authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death "High Risk Product". By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*//**
 ******************************************************************************
 ** \file   mcu.h
 **
 ** Header File for device dependent includes
 **
 ** History:
 ** 03.09.2015  MSCH, ACEH, Automatic generated by McuTemplateGen
 **
 ******************************************************************************/
#ifndef __MAIN_MCU_H__
#define __MAIN_MCU_H__

/******************************************************************************
 ** \brief Include RTE Device
 ** 
 ******************************************************************************/

#ifndef __RTE_DEVICE_H
  #include "RTE_Device.h"
#endif

extern void ExtifIrqHandler();
extern void IRQ049_Handler();

#include "pdl/common/mcu.h"

/******************************************************************************
 ** \brief MCU header file include
 ** 
 ******************************************************************************/


/******************************************************************************
 ** \brief MCU system start-up header file include
 ** 
 ******************************************************************************/

/******************************************************************************
 ** \brief GPIO macros
 ** 
 ******************************************************************************/


#include "pdl_header.h"


/* we include the PDL's mcu.h here, too so that the corect defines get set, too*/

#endif  /* __MCU_H__ */
